spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/bookdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: kafka:9092
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8081